name: cached_network_image
description: Flutter library to load and cache network images.
  Can also be used with placeholder and error widgets.
homepage: https://github.com/Baseflow/flutter_cached_network_image
topics:
  - cache
  - image
  - network-image
version: 3.4.1

environment:
  sdk: ^3.0.0
  flutter: '>=3.10.0'

dependencies:
  cached_network_image_platform_interface:
    git:
      url: https://github.com/vudvv/cached_network_image_platform_interface
      ref: 4.1.2
  cached_network_image_web:
    git:
      url: https://github.com/vudvv/cached_network_image_web
      ref: 1.3.2
  flutter:
    sdk: flutter
  flutter_cache_manager:
    git:
      url: https://github.com/vudvv/flutter_cache_manager
      ref: 3.4.2
  octo_image: ^2.1.0

dev_dependencies:
  file: '>=7.0.0 <8.0.0'
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
